### ISSUE TITLE
Update GitHub Actions based workflows

### ISSUE THREAD

**Issue by damianooldoni** [riparias/vmm-rattenapp-occurrences#258]
@hansvancalster is helping us to improve actions, less work for maintainers with tokens generation (every 90 days or so) and possibly even safer.

Example:

Remove this line https://github.com/riparias/vmm-rattenapp-occurrences/blob/b63c0e4b69341b8aa0374eb01bfe9882e5c5d803/.github/workflows/fetch-data.yaml#L28C33-L28C42 to use standard GITHUB_TOKEN (with write permissions to be set) which generates a temporary 24h valid-only token.

Permissions must to be set at the beginning (see https://github.com/inbo/tutorials/issues/360#issuecomment-2766108500):

```
permissions:
  contents: write  # Required for committing and pushing changes
  pull-requests: write  # Required for creating and updating pull requests
  actions: read  # Required for reading actions
```` 
Remove comments.

Also, try to remove https://github.com/riparias/vmm-rattenapp-occurrences/blob/b63c0e4b69341b8aa0374eb01bfe9882e5c5d803/.github/workflows/mapping_and_testing.yaml#L22 as github_PAT is not used.
